//Bilderna kommer från http://www.clker.com/ och har ingen copyright, ok att använda
//Text till bilderna i en array
//textBank array skapas i nb_global.js så att den är global
//http://www.tiger.se/dok/koder.html
//ö	&ouml;	&#246;
//Ö	    	&#214;
//ä	&auml;	&#228;
//å	&aring;	&#229;
//é	&eacute;	&#233;
//Ä 196


textBank[0]="Boll";
textBank[1]="Spett";
textBank[2]="T"+String.fromCharCode(229);
textBank[3]="F"+String.fromCharCode(233);
textBank[4]="Myra";
textBank[5]="Hem";
textBank[6]="Kex";
textBank[7]="Sjukhus";
textBank[8]="R"+String.fromCharCode(229)+"tta";
textBank[9]="Bio";
textBank[10]="Dass";
textBank[11]="Dator";
textBank[12]="Dun";
textBank[13]="Damm";
textBank[14]="D"+String.fromCharCode(246)+"rr";
textBank[15]="Tall";
textBank[16]="Doja";
textBank[17]="Tak";
textBank[18]="Duva";
textBank[19]="Dop";
textBank[20]="Raket";
textBank[21]="T"+String.fromCharCode(228)+"rning";
textBank[22]="Neon-skylt";
textBank[23]="Nemo";
textBank[24]="Nero";
textBank[25]="Pengar";
textBank[26]="Najad 26 - Segelb"+String.fromCharCode(229)+"t";
textBank[27]="Nacke (Supersaurus)";
textBank[28]="Nav";
textBank[29]="Napp";
textBank[30]="Mast";
textBank[31]="Mat";
textBank[32]="Man";
textBank[33]="Mick";
textBank[34]="Margarin";
textBank[35]="Mal";
textBank[36]="Maya-Indian";
textBank[37]="Mack";
textBank[38]="Maffia";
textBank[39]="Mapp";
textBank[40]="Ris";
textBank[41]="Ratt";
textBank[42]="Jorden";
textBank[43]="Ram";
textBank[44]="R"+String.fromCharCode(246)+"r";
textBank[45]="Rulle";
textBank[46]="Rio";
textBank[47]="Tennisrack";
textBank[48]="(Gitarr-)Riff";
textBank[49]="Rep";
textBank[50]="Lasso";
textBank[51]="Latte";
textBank[52]="Flygplan";
textBank[53]="Lamm";
textBank[54]="Lerfigur";
textBank[55]="Lollipop";
textBank[56]="Lian";
textBank[57]="Lack";
textBank[58]="Lava";
textBank[59]="Lapp";
textBank[60]="Jazz";
textBank[61]="Gadd";
textBank[62]="Sked";
textBank[63]="Kemtv"+String.fromCharCode(228)+"tt";
textBank[64]="Giraff";
textBank[65]="Hjul";
textBank[66]="Lucifer";
textBank[67]="Jacka";
textBank[68]="Jaffa";
textBank[69]="Chokladbit";
textBank[70]="Kasse";
textBank[71]="Katt";
textBank[72]="Kona";
textBank[73]="Kam";
textBank[74]="Badkar";
textBank[75]="Is";
textBank[76]="Kaj";
textBank[77]="Pepparkaka";
textBank[78]="Kaffe";
textBank[79]="Kappa";
textBank[80]="Vas";
textBank[81]="Fat";
textBank[82]="Fanta";
textBank[83]="Ljungv"+String.fromCharCode(228)+"gen";
textBank[84]="Fyr";
textBank[85]="Val";
textBank[86]="Vajer";
textBank[87]="Fackla";
textBank[88]="Vovve";
textBank[89]="Vippa";
textBank[90]="(Bas-)Fiol";
textBank[91]="Bank";
textBank[92]="(F1-)Bana";
textBank[93]="(J"+String.fromCharCode(228)+"rnv"+String.fromCharCode(228)+"gs-)Bom";
textBank[94]="Bar";
textBank[95]="(H"+String.fromCharCode(246)+"-)Bal";
textBank[96]="Paj - PI";
textBank[97]="Back(-Hopp)";
textBank[98]="(Kalas-)Puff";
textBank[99]="Hockeyklubba (Gretzky)";
textBank[100]="Dusch";
